### ISSUE TITLE
invalid project link

### ISSUE THREAD

**Issue by AMDphreak** [chrismah/ClickMonitorDDC7.2_Manual#1]
[https://www.clickmonitorddc.bplaced.net/](https://www.clickmonitorddc.bplaced.net/)
invalid link. Any idea where the project has moved?

**Comment by chrismah** [comment]
Hey,

Unfortunately I think the project is dead. I just scraped what information
I could find from some online caches.

Cheers,
Chris

**Comment by bpsib** [comment]
Portable version can be downloaded from https://web.archive.org/web/20201001204420if_/https://clickmonitorddc.bplaced.net/ClickMonitorDDC_7_2.zip and should be added here along with the setup version.
