### ISSUE TITLE
How do I switch monitor-input on multiple displays - hotkey

### ISSUE THREAD

**Issue by RadekPelikan** [chrismah/ClickMonitorDDC7.2_Manual#11]
How do I set up a hot key so that I would switch between monitor inputs DisplayPort | HDMI1?
I've tried a couple of approaches, and none of them seemed to work.
![image](https://github.com/chrismah/ClickMonitorDDC7.2/assets/79970400/6f1d3818-76e4-448b-93cc-5b7a7c977fd5)
![image](https://github.com/chrismah/ClickMonitorDDC7.2/assets/79970400/4554b4a1-830f-4897-b128-7649accc56b3)
![image](https://github.com/chrismah/ClickMonitorDDC7.2/assets/79970400/d4538897-eb27-4716-9513-de0b455b7bf5)

**Comment by chrismah** [comment]
Hey,

Not 100% sure if it'll resolve your issue but here is what my working Hotkeys look like:

![screenshot](https://github.com/chrismah/ClickMonitorDDC7.2/assets/1733604/8a585057-894b-41f4-a0a7-b7dabe93820c)

Also to note, apparently LG monitors don't accept DDC signals for input switching. So depending on what model you have that could also be an issue.

Cheers
