### ISSUE TITLE
Help with CPC and Lea Refresh

### ISSUE THREAD

**Issue by Krassikn** [chrismah/ClickMonitorDDC7.2_Manual#12]
Hello, I really admire your work. Is it possible to add an on/off toggle for CPC and Lea Refresh, which can be found in the service menu of LG monitors? Its it possible VCP codes for CPC and Lea Refresh be retrieved?

**Comment by chrismah** [comment]
Hey, sorry I am not the actual creator of this software. Just have it hosted for reference / sharing. Cheers
