### ISSUE TITLE
Informations on the Original Developper

### ISSUE THREAD

**Issue by ACIXCIX0001** [chrismah/ClickMonitorDDC7.2_Manual#3]
Evening !

This Software is absolutely wild !

Do you know who is the original developper or team ?

Do you you know how the commands to control the GPU vibrance | saturation by DDC actually works ?
Outside the Dedicated GPU Drivers like Nvidia Control Panel no other software is able to control the Vibrance Output from the GPU.....

Any Informations ??

**Comment by chrismah** [comment]
Hey!

Sorry I don’t have much information on the original developer… I had stumbled across this software ages ago but couldn’t find any documentation on how to operate it fully. I eventually found a cached copy and just copied it for future reference :)

Iirc, the software is using a monitor specific protocol present in most monitors. Doesn’t need GPU drivers/interaction at all.

Sorry can’t be of more help, cheers!
Chris

**Comment by ACIXCIX0001** [comment]
Thank for your answer !
These developers developed an uncommon software without being known from anyone.......

**Comment by raddyst** [comment]
> These developpers devlopped an exceptional software without being known from anyone.......

Try **Martin <mapini@freenet.de>** - https://web.archive.org/web/20200910145554/https://clickmonitorddc.bplaced.net/

**Comment by ACIXCIX0001** [comment]
ok thank.
yes the archived webpage, apparently this is the martin mapini the developper.
Though do you know another software that can control the contrast | vibrance like that ?

**Comment by raddyst** [comment]
> Though do you know another software that can control the contrast | vibrance like that ?

May be https://github.com/emoacht/Monitorian

**Comment by ACIXCIX0001** [comment]
Only the Brightness, not the saturation, vibrance...

**Comment by raddyst** [comment]
> Only the Brightness

Brightness & contrast

**Comment by ACIXCIX0001** [comment]
> > Only the Brightness
> 
> Brightness & contrast

yes I meant saturation and vibrance : other software that can do that ?

**Comment by raddyst** [comment]
> other software that can do that ?

Check https://www.entechtaiwan.com/lib/softmccs.shtm

**Comment by ACIXCIX0001** [comment]
thank for the link as soon as possible
also only old softwares, no one is working on saturation and vibrance control outside nvidia control panel these days....

**Comment by momongah** [comment]
> thank for the link as soon as possible also only old softwares, no one is working on saturation and vibrance control outside nvidia control panel these days....

be the change you want to see in the world, you should make it
