### ISSUE TITLE
systray: mouse wheel suddenly lagging/delayed

### ISSUE THREAD

**Issue by alfarme** [chrismah/ClickMonitorDDC7.2_Manual#4]
Hi,

first off, I love your little piece of software, I use it religiously every day :)

I realize this might not ever get seen/get a reply, but: out of nowhere I can't use the mouse wheel to change brightness anymore, the lag between me using the mouse wheel over the systray icon, and the software responding is liek 10 seconds. same delay to open the tool via systray. 

help! :)
-alfarme

**Comment by bpsib** [comment]
Have you got "reread values" on in settings? Try turning it off if you have and that should speed it up.

**Comment by alfarme** [comment]
yes I did, and disabling it fixed the issue! so simple but I never tried that, haha.

thank you so much, this makes my life so much easier again :) :)

and thanks again for this amazing little tool ! :D
